"""artoo-deck: slide machinery for presentation artifacts.

A deck is a different reading mode from an article, not a variant of one:
one frame at a time, an act structure, speaker notes, and a landscape page
when printed. This library supplies that machinery so a presentation
artifact is authored as content rather than rebuilt as chrome each time.

Every class is prefixed ``deck-``. That prefix is load-bearing: chrome and
content share one stylesheet, and an unprefixed chrome class will silently
capture a content element using the same word. Because the prefix is a real
rule rather than a convention, it is also declared as a namespace below —
``artoo build`` reports a ``deck-`` class the stylesheet does not define,
whether it is a guess at library vocabulary or an author's own class parked
in a namespace it should stay out of.
"""

from pathlib import Path

from .. import Library

VERSION = "0.1.0"

NAMESPACES = ("deck-",)

CLASSES = {
    # Frame and chrome.
    "deck-root": "on `<body>`; carries the deck's redefinable `--deck-*` tokens",
    "deck-bar": "fixed top chrome holding the mark, toggles, and pager",
    "deck-mark": "the initial or logo mark in the bar",
    "deck-who": "the deck's name in the bar",
    "deck-spacer": "flexible gap pushing bar items apart",
    "deck-pager": "prev / counter / next group in the bar",
    "deck-pager-m": "the mobile pager, shown only on narrow screens",
    "deck-counter": "slide counter; deck.js writes into `[data-deck-counter]`",
    "deck-progress": "progress rail; its inner `<i data-deck-progress>` is the fill",
    # Slides.
    "deck-stage": "slide container; must carry `data-deck` for deck.js to find it",
    "deck-slide": "one slide; `data-act` groups it in the overview, `data-short` labels it",
    "deck-inner": "the slide's content box, centered and width-capped",
    "deck-eyebrow": "small rule-trailing label above the slide heading",
    "deck-lede": "opening line on a title slide",
    "deck-notes": "speaker note; hidden until toggled, and printed with the slide",
    # Content vocabulary.
    "deck-stat-row": "row of figures on a slide",
    "deck-stat": "one figure; `<b>` the value, `<span>` its label",
    "deck-grid": "ruled column layout; add `two`, `three`, or `four`",
    "deck-cell": "one cell of a `deck-grid`; `<b>` heading, `<p>` body",
    "deck-facts": "ruled key/value list; `.k` is the key, `.v` the value",
    "deck-callout": "the sentence you want repeated back to you; `cool` tints it",
    "deck-figure": "figure on a slide; a direct child `<svg>` is sized to fit",
    "deck-table-wrap": "scroll container for a table too wide for the frame",
    # Generated by deck.js — read these, do not author them.
    "deck-overview": "overview panel root; mark it `data-deck-overview` and deck.js fills it",
    "deck-ov-act": "one act group inside the overview (generated)",
    "deck-ov-grid": "the slide grid within an act (generated)",
    "deck-ov-item": "one slide thumbnail in the overview (generated)",
    "deck-help": "keyboard-help overlay; mark it `data-deck-help`",
    "deck-help-card": "the card inside the help overlay",
}

library = Library(
    name="artoo-deck",
    version=VERSION,
    summary="Slides: acts, speaker notes, overview, keyboard/touch nav, landscape print.",
    root=Path(__file__).parent / "assets",
    namespaces=NAMESPACES,
    classes=CLASSES,
)
