"""``AGENTS.md``: the artifact's usage contract, written where it is needed.

An artifact is meant to be built by whoever owns its subject, from inside
their repo — increasingly a coding agent rather than a person. That reader has
the artifact directory in front of them and nothing else: artoo's own README,
DESIGN.md, and the library READMEs are all in a different repo or inside an
installed wheel. Faced with a starter page and four vendored stylesheets, the
only available move is to reverse-engineer the layout, or to copy a previous
artifact and inherit whatever was wrong with it.

So the contract travels with the artifact. ``AGENTS.md`` is the vendor-neutral
filename most coding agents already read unprompted, which is why it is the
carrier rather than something artoo-specific.

Two properties make it trustworthy. It is generated from the stylesheets
*this* artifact actually vendored, so it cannot advertise a class that is not
there. And it is generated into a marked block, so regenerating it on
``artoo lib update`` never destroys notes someone wrote around it.
"""

from __future__ import annotations

from pathlib import Path

from . import __version__, markup
from . import libraries as libraries_mod
from .manifest import Manifest

GUIDE_NAME = "AGENTS.md"

BEGIN = "<!-- artoo:begin -->"
END = "<!-- artoo:end -->"

_PREAMBLE = f"""{BEGIN}
<!-- Generated by artoo {{version}}. Rewritten by `artoo init` and
     `artoo lib add|update`; edits inside this block are lost. Anything you
     write outside it is kept. -->"""

_TAIL = """## Notes for this artifact

<!-- Yours. Everything below the marker above survives regeneration: the
     reader decision, house conventions, what this piece must not claim. -->
"""


def _commands(m: Manifest) -> str:
    return f"""## Commands

Every command takes an artifact path, or resolves upward from the working
directory if you omit it.

| goal | command |
|------|---------|
| manifest health, firewall report, library drift | `artoo status {m.slug}` |
| refresh inputs, verify, stamp `updated` | `artoo build {m.slug}` |
| publish (firewall-staged) | `artoo deploy {m.slug}` |
| the layout vocabulary, in full | `artoo docs <library>` |
| everything artoo knows | `artoo docs --all` |

`artoo build` is the check that matters: it runs the manifest's build
commands, refreshes the provenance projection, verifies the firewall, and
reports any class used here that its library does not define."""


def _firewall(m: Manifest) -> str:
    return f"""## What publishes

Only `{m.site}/`. The artifact directory around it — `work/`, `notebook/`,
`artifact.toml`, this file — stays in the repo. Inside `{m.site}/` the firewall
still withholds any path segment starting with `_` or `.` (except
`.nojekyll`), and the research filenames `notebook.md`, `notes.md`,
`priors.md`, `DECISIONS.md`, `HANDOFF.md`.

That is deny-by-default and structural: `{m.site}/_draft/v2.html` is visible to
you and invisible to the world with no configuration. Put working material in
`work/`, and drafts under a `_`-prefixed path.

`artoo status {m.slug}` lists exactly what is being withheld."""


def _vocabulary(m: Manifest) -> str:
    """Class tables for the libraries this artifact actually carries.

    Generated from the vendored bytes rather than from the installed library:
    an artifact keeps rendering at the version it vendored, and a table
    describing some other version would be worse than no table at all.
    """
    sections = []
    for entry in m.libraries:
        name = entry.get("name", "")
        vendored = libraries_mod.vendored_dir(m, name)
        if not vendored.is_dir():
            continue
        try:
            lib = libraries_mod.get(name)
        except KeyError:
            continue
        if not lib.classes:
            continue
        present = markup.base_classes_in_dir(vendored)
        rows = "\n".join(
            f"| `{cls}` | {role} |" for cls, role in lib.classes.items() if cls in present
        )
        if not rows:
            continue
        version = entry.get("version", lib.version)
        header = (
            f"### {name} {version}\n\n"
            f"{lib.summary}\n\n"
            f"Vendored at `{m.site}/lib/{name}/`. Read the stylesheets there if you "
            f"need the exact rule; this table is the vocabulary they define.\n\n"
            f"| class | role |\n|---|---|\n{rows}"
        )
        if lib.namespaces:
            owned = ", ".join(f"`{ns}`" for ns in lib.namespaces)
            header += (
                f"\n\nThis library owns {owned}. A class starting with one of those "
                f"that the stylesheet does not define is a guess, and `artoo build` "
                f"fails on it and names the nearest real class. Your own classes go "
                f"outside those prefixes — they are never second-guessed."
            )
        header += f"\n\nFull prose contract: `artoo docs {name}`."
        sections.append(header)
    if not sections:
        return ""
    return "## Layout vocabulary\n\n" + "\n\n".join(sections)


def _rules(m: Manifest) -> str:
    research = ""
    if m.notebook:
        research = (
            f"\n5. **Research goes in `{m.notebook}/`, corrections go through artoo.** "
            f"Edit the notebook with flip or with `artoo feedback {m.slug} \"…\"`; "
            f"the projection under `{m.site}/data/` is generated and will be "
            f"overwritten on the next build."
        )
    return f"""## Rules

1. **Use the vocabulary above; do not invent classes in its namespaces.** An
   invented class renders as nothing, which looks like a styling bug and is
   not one.
2. **Nothing loads from the network.** The artifact must render from a
   `file://` URL — no CDN scripts, no remote fonts, no external stylesheets.
   Vendor a runtime with `artoo lib vendor <name> <url>` and it is recorded
   with a pinned hash.
3. **Style SVG with CSS, not presentation attributes.** `fill="var(--chart-1)"`
   never resolves — SVG presentation attributes are not CSS. Give the shape a
   class and set `fill` in a `<style>` block, which also lets the chart follow
   the theme instead of baking one that only reads in light mode.
4. **A figure earns its place by enabling a valid comparison.** Vintages,
   denominators, and a source note belong in the `figcaption`.{research}"""


def render(m: Manifest) -> str:
    """The managed block for this artifact, markers included."""
    parts = [
        _PREAMBLE.format(version=__version__),
        f"# {m.title}",
        f"This directory is an **artoo artifact**: a self-contained HTML mini-site "
        f"(`{m.site}/`) paired with the research behind it. `artifact.toml` is its "
        f"source of truth — kind `{m.kind}`, slug `{m.slug}`.",
        _commands(m),
        _firewall(m),
        _vocabulary(m),
        _rules(m),
        "## More\n\n"
        "`artoo docs` lists every topic — the manifest format, the firewall, the "
        "provenance roundtrip, the generators. `artoo docs --all` prints the lot "
        "in one read.",
        END,
    ]
    return "\n\n".join(part for part in parts if part).rstrip() + "\n"


def write(m: Manifest) -> Path:
    """Write or refresh ``AGENTS.md``, preserving anything outside the block."""
    path = m.dir / GUIDE_NAME
    block = render(m)

    if not path.is_file():
        path.write_text(f"{block}\n{_TAIL}", encoding="utf-8")
        return path

    existing = path.read_text(encoding="utf-8")
    start = existing.find(BEGIN)
    end = existing.find(END)
    if start == -1 or end == -1 or end < start:
        # Someone wrote their own AGENTS.md before artoo did. Their text is the
        # more specific instruction, so it stays first and keeps the last word.
        path.write_text(f"{existing.rstrip()}\n\n{block}", encoding="utf-8")
        return path

    updated = existing[:start] + block.rstrip() + existing[end + len(END) :]
    path.write_text(updated, encoding="utf-8")
    return path
