"""Deterministic JSON data packing for offline artifacts."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from .manifest import Manifest


@dataclass
class PackResult:
    written: list[Path] = field(default_factory=list)
    problems: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.problems


def pack(m: Manifest, *, dry_run: bool = False) -> PackResult:
    """Copy declared JSON into site/ and write a matching file:// loader."""
    result = PackResult()
    for entry in m.data_packs:
        source_name = str(entry.get("source", ""))
        path_name = str(entry.get("path", ""))
        global_name = str(entry.get("global", ""))
        script_name = str(entry.get("script", "")) or str(Path(path_name).with_suffix(".js"))
        if not source_name or not path_name or not global_name:
            result.problems.append(
                "[[data]] needs source, path, and global; fix the entry in artifact.toml"
            )
            continue
        if any(
            Path(value).is_absolute() or ".." in Path(value).parts
            for value in (path_name, script_name)
        ):
            result.problems.append(
                "[[data]] path and script must stay inside build.site; fix artifact.toml"
            )
            continue
        source = m.dir / source_name
        if not source.is_file():
            result.problems.append(
                f"data source {source_name} does not exist; create it or remove its [[data]] entry"
            )
            continue
        try:
            value = json.loads(source.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            result.problems.append(f"data source {source_name} is not valid JSON: {exc}")
            continue
        if dry_run:
            continue
        json_dest = m.site_dir / path_name
        js_dest = m.site_dir / script_name
        json_dest.parent.mkdir(parents=True, exist_ok=True)
        js_dest.parent.mkdir(parents=True, exist_ok=True)
        json_dest.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        js_dest.write_text(
            "/* Generated by artoo. The sibling JSON is canonical; this global "
            "keeps file:// usable. */\n"
            f"window.{global_name} = {json.dumps(value, ensure_ascii=False)};\n",
            encoding="utf-8",
        )
        result.written.extend((json_dest, js_dest))
    return result
