"""Evidence ingestion: project neutral evidence or an attached flip notebook.

The read half of the flip roundtrip. When an artifact has an associated flip
notebook, ``ingest`` runs ``flip export json`` (the policy-filtered
``flip-render/1`` projection) and lands it at ``site/data/provenance.json`` —
the canonical, machine-readable lineage the kit's provenance panel and any
other consumer read. It also writes a tiny ``site/data/provenance.js`` global
loader so the panel hydrates from a ``file://`` URL with no server, and records
the notebook's ``uid``+``updated`` in ``artifact.toml`` as the render vintage
that ``artoo status`` later checks for staleness.

Declared neutral evidence is a build contract, so a missing or invalid source
is an error. The Flip adapter remains best-effort: no Flip, no notebook, or a
policy refusal is a skip with a note. Artoo core works without Flip installed.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from . import flip_read
from .manifest import Manifest

DATA_DIR = "data"
PROVENANCE_JSON = "provenance.json"
PROVENANCE_JS = "provenance.js"


@dataclass
class ProvenanceResult:
    status: str  # "written" | "skipped" | "error"
    note: str = ""
    path: Path | None = None
    vintage: dict = field(default_factory=dict)
    counts: dict = field(default_factory=dict)
    data: dict = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return self.status != "error"


def attached_notebook(m: Manifest) -> Path | None:
    """The artifact's flip notebook directory, if one is declared and present.

    An artifact associates a notebook through ``[research] notebook = <dir>``
    (the same key ``artoo init --notebook`` and the explainer generator set).
    A directory carrying an ``index.md`` is a flip notebook root.
    """
    nb = m.notebook_dir
    if nb and (nb / "index.md").is_file():
        return nb
    return None


def _counts(data: dict) -> dict:
    sources = data.get("sources", []) or []
    claims = data.get("claims", []) or []
    grades: dict[str, int] = {}
    for s in sources:
        grade = s.get("grade") or "?"
        grades[grade] = grades.get(grade, 0) + 1
    load_bearing = sum(1 for c in claims if c.get("load_bearing"))
    return {
        "sources": len(sources),
        "grades": grades,
        "claims": len(claims),
        "load_bearing": load_bearing,
        "sessions": len(data.get("sessions", []) or []),
    }


def _write_projection(
    m: Manifest,
    data: dict,
    *,
    vintage: dict | None = None,
    generated_from: str,
) -> ProvenanceResult:
    data_dir = m.site_dir / DATA_DIR
    data_dir.mkdir(parents=True, exist_ok=True)
    dest = data_dir / PROVENANCE_JSON
    dest.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    js = data_dir / PROVENANCE_JS
    js.write_text(
        f"/* Generated by artoo from {generated_from}. The sibling JSON is canonical. */\n"
        "window.__ARTOO_PROVENANCE__ = "
        + json.dumps(data, ensure_ascii=False)
        + ";\n",
        encoding="utf-8",
    )
    return ProvenanceResult(
        "written",
        path=dest,
        vintage=vintage or {},
        counts=_counts(data),
        data=data,
    )


def _read_neutral(m: Manifest) -> tuple[dict | None, str]:
    source = m.dir / m.evidence_source
    if not source.is_file():
        return None, (
            f"evidence source {m.evidence_source} does not exist; create it or remove "
            "[evidence] from artifact.toml"
        )
    try:
        data = json.loads(source.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return None, f"evidence source {m.evidence_source} is invalid: {exc}"
    problems = evidence_problems(data)
    if problems:
        return None, f"evidence source {m.evidence_source}: " + "; ".join(problems)
    return data, ""


def evidence_source_problems(m: Manifest) -> list[str]:
    if not m.evidence_source:
        return []
    _, problem = _read_neutral(m)
    return [problem] if problem else []


def _neutral(m: Manifest) -> ProvenanceResult:
    data, problem = _read_neutral(m)
    if data is None:
        return ProvenanceResult("error", note=problem)
    return _write_projection(m, data, generated_from=m.evidence_source)


def evidence_problems(data: object) -> list[str]:
    """Validate the small provider-neutral ``artoo-evidence/1`` contract."""
    if not isinstance(data, dict):
        return ["root must be a JSON object"]
    problems = []
    if data.get("contract") != "artoo-evidence/1":
        problems.append('contract must be "artoo-evidence/1"')
    sources = data.get("sources", [])
    claims = data.get("claims", [])
    if not isinstance(sources, list):
        problems.append("sources must be an array")
        sources = []
    if not isinstance(claims, list):
        problems.append("claims must be an array")
        claims = []
    source_ids = set()
    for index, source in enumerate(sources):
        if (
            not isinstance(source, dict)
            or not isinstance(source.get("id"), str)
            or not source.get("id")
            or not isinstance(source.get("title"), str)
            or not source.get("title")
        ):
            problems.append(f"sources[{index}] needs id and title")
            continue
        if source["id"] in source_ids:
            problems.append(f"sources[{index}] repeats id {source['id']}")
        source_ids.add(source["id"])
    claim_ids = set()
    for index, claim in enumerate(claims):
        if (
            not isinstance(claim, dict)
            or not isinstance(claim.get("id"), str)
            or not claim.get("id")
            or not isinstance(claim.get("text"), str)
            or not claim.get("text")
        ):
            problems.append(f"claims[{index}] needs id and text")
            continue
        if claim["id"] in claim_ids:
            problems.append(f"claims[{index}] repeats id {claim['id']}")
        if claim["id"] in source_ids:
            problems.append(f"claims[{index}] id {claim['id']} is already a source id")
        claim_ids.add(claim["id"])
        refs = claim.get("sources", [])
        if not isinstance(refs, list) or not all(isinstance(ref, str) for ref in refs):
            problems.append(f"claims[{index}].sources must be an array of ids")
            continue
        unknown = sorted(set(refs) - source_ids)
        if unknown:
            problems.append(f"claims[{index}] cites unknown sources: {', '.join(unknown)}")
    return problems


def ingest(m: Manifest) -> ProvenanceResult:
    """Project declared evidence, otherwise adapt an attached flip notebook."""
    if m.evidence_source:
        return _neutral(m)
    nb = attached_notebook(m)
    if nb is None:
        return ProvenanceResult(
            "skipped",
            note="no flip notebook attached ([research] notebook), or it has no index.md",
        )

    if not flip_read.available():
        return ProvenanceResult(
            "skipped",
            note="flip is not installed; provenance projection unavailable",
        )

    data, reason = flip_read.export_json(nb, include_private=m.research_include_private)
    if data is None:
        # flip's own refusal is correct but names flip's remedy — "pass
        # --include-private" — and there is no such flag on `artoo
        # provenance`. Whoever reads this is holding artifact.toml, so the
        # message has to name the key they can actually set. Left verbatim
        # otherwise: the visibility policy is flip's to state.
        if not m.research_include_private and "--include-private" in reason:
            reason = reason.replace(
                "or pass --include-private",
                'or opt in deliberately with `include_private = true` under '
                '[research] in artifact.toml (this artifact then renders a '
                'non-public notebook in full — check the deploy firewall before '
                'publishing it)',
            )
        return ProvenanceResult("error", note=reason)

    nb_meta = data.get("notebook", {}) or {}
    vintage = {"uid": nb_meta.get("uid", ""), "updated": nb_meta.get("updated", "")}
    if m.path is not None and (
        m.rendered_uid != vintage["uid"] or m.rendered_updated != vintage["updated"]
    ):
        m.rendered_uid = vintage["uid"]
        m.rendered_updated = vintage["updated"]
        m.save()

    return _write_projection(
        m,
        data,
        vintage=vintage,
        generated_from="flip export json",
    )


# -- data/ JSON validation ----------------------------------------------------


def data_json_problems(site_dir: Path) -> list[str]:
    """Parse every ``*.json`` under ``site/data/``; report unparseable ones.

    Site data files are consumed by the browser (and by other tools); a JSON
    syntax error there is a silent runtime break, so ``status`` and ``build``
    surface it as a finding.
    """
    problems: list[str] = []
    data_dir = site_dir / DATA_DIR
    if not data_dir.is_dir():
        return problems
    for path in sorted(data_dir.rglob("*.json")):
        if not path.is_file():
            continue
        try:
            json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            rel = path.relative_to(site_dir.parent) if site_dir.parent in path.parents else path
            problems.append(f"invalid JSON in {rel}: {exc}")
    return problems


# -- staleness ----------------------------------------------------------------


def staleness(m: Manifest) -> dict:
    """Compare the recorded render vintage against the live notebook.

    Returns ``{"state": ..., "detail": ...}`` where state is:
      - ``"none"``    — no notebook attached (nothing to compare);
      - ``"unknown"`` — a notebook is declared but not readable;
      - ``"never"``   — notebook present but the site was never rendered from it;
      - ``"fresh"``   — recorded vintage matches the live notebook;
      - ``"stale"``   — the notebook has moved on since the render.
    Never a hard failure — staleness is advisory.
    """
    nb = m.notebook_dir
    if not nb or not m.notebook:
        return {"state": "none", "detail": ""}
    live = flip_read.read_vintage(nb)
    if live is None:
        return {"state": "unknown", "detail": f"notebook at {m.notebook} is not readable"}
    if not m.rendered_uid and not m.rendered_updated:
        return {
            "state": "never",
            "detail": "site has no recorded notebook vintage — run `artoo provenance`",
        }
    if m.rendered_uid and live.get("uid") and m.rendered_uid != live["uid"]:
        return {
            "state": "stale",
            "detail": (
                f"rendered from notebook {m.rendered_uid}, but the attached "
                f"notebook is {live['uid']} — a different notebook"
            ),
        }
    if m.rendered_updated != live.get("updated", ""):
        return {
            "state": "stale",
            "detail": (
                f"rendered from {m.rendered_updated or '(unstamped)'}, "
                f"notebook now updated {live.get('updated') or '(unstamped)'} — re-render"
            ),
        }
    return {"state": "fresh", "detail": f"render matches notebook {live.get('updated')}"}
