"""Provenance ingestion: project an attached flip notebook into the site.

The read half of the flip roundtrip. When an artifact has an associated flip
notebook, ``ingest`` runs ``flip export json`` (the policy-filtered
``flip-render/1`` projection) and lands it at ``site/data/provenance.json`` —
the canonical, machine-readable lineage the kit's provenance panel and any
other consumer read. It also writes a tiny ``site/data/provenance.js`` global
loader so the panel hydrates from a ``file://`` URL with no server, and records
the notebook's ``uid``+``updated`` in ``artifact.toml`` as the render vintage
that ``artoo status`` later checks for staleness.

Everything here is best-effort: no flip, no notebook, or a policy refusal is a
*skip with a note*, never a build failure. artoo core keeps working without
flip installed.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from . import flip_read
from .manifest import Manifest

DATA_DIR = "data"
PROVENANCE_JSON = "provenance.json"
PROVENANCE_JS = "provenance.js"


@dataclass
class ProvenanceResult:
    status: str  # "written" | "skipped" | "error"
    note: str = ""
    path: Path | None = None
    vintage: dict = field(default_factory=dict)
    counts: dict = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return self.status != "error"


def attached_notebook(m: Manifest) -> Path | None:
    """The artifact's flip notebook directory, if one is declared and present.

    An artifact associates a notebook through ``[research] notebook = <dir>``
    (the same key ``artoo init --notebook`` and the explainer generator set).
    A directory carrying an ``index.md`` is a flip notebook root.
    """
    nb = m.notebook_dir
    if nb and (nb / "index.md").is_file():
        return nb
    return None


def _counts(data: dict) -> dict:
    sources = data.get("sources", []) or []
    claims = data.get("claims", []) or []
    grades: dict[str, int] = {}
    for s in sources:
        grade = s.get("grade") or "?"
        grades[grade] = grades.get(grade, 0) + 1
    load_bearing = sum(1 for c in claims if c.get("load_bearing"))
    return {
        "sources": len(sources),
        "grades": grades,
        "claims": len(claims),
        "load_bearing": load_bearing,
        "sessions": len(data.get("sessions", []) or []),
    }


def ingest(m: Manifest) -> ProvenanceResult:
    """Project the attached notebook into ``site/data/`` and stamp the vintage."""
    nb = attached_notebook(m)
    if nb is None:
        return ProvenanceResult(
            "skipped",
            note="no flip notebook attached ([research] notebook), or it has no index.md",
        )

    if not flip_read.available():
        return ProvenanceResult(
            "skipped",
            note="flip is not installed; provenance projection unavailable",
        )

    data, reason = flip_read.export_json(nb, include_private=m.research_include_private)
    if data is None:
        return ProvenanceResult("error", note=reason)

    data_dir = m.site_dir / DATA_DIR
    data_dir.mkdir(parents=True, exist_ok=True)
    dest = data_dir / PROVENANCE_JSON
    payload = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    dest.write_text(payload, encoding="utf-8")

    # A ``window`` global so the panel hydrates offline (a bare fetch() of a
    # sibling JSON is blocked under file://; a <script> assignment is not).
    js = data_dir / PROVENANCE_JS
    js.write_text(
        "/* Generated by artoo from flip export json. Offline (file://) loader\n"
        "   for the artoo-kit provenance panel; the canonical data is the sibling\n"
        "   provenance.json. */\n"
        "window.__ARTOO_PROVENANCE__ = "
        + json.dumps(data, ensure_ascii=False)
        + ";\n",
        encoding="utf-8",
    )

    nb_meta = data.get("notebook", {}) or {}
    vintage = {"uid": nb_meta.get("uid", ""), "updated": nb_meta.get("updated", "")}
    if m.path is not None and (
        m.rendered_uid != vintage["uid"] or m.rendered_updated != vintage["updated"]
    ):
        m.rendered_uid = vintage["uid"]
        m.rendered_updated = vintage["updated"]
        m.save()

    return ProvenanceResult(
        "written", path=dest, vintage=vintage, counts=_counts(data)
    )


# -- data/ JSON validation ----------------------------------------------------


def data_json_problems(site_dir: Path) -> list[str]:
    """Parse every ``*.json`` under ``site/data/``; report unparseable ones.

    Site data files are consumed by the browser (and by other tools); a JSON
    syntax error there is a silent runtime break, so ``status`` and ``build``
    surface it as a finding.
    """
    problems: list[str] = []
    data_dir = site_dir / DATA_DIR
    if not data_dir.is_dir():
        return problems
    for path in sorted(data_dir.rglob("*.json")):
        if not path.is_file():
            continue
        try:
            json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            rel = path.relative_to(site_dir.parent) if site_dir.parent in path.parents else path
            problems.append(f"invalid JSON in {rel}: {exc}")
    return problems


# -- staleness ----------------------------------------------------------------


def staleness(m: Manifest) -> dict:
    """Compare the recorded render vintage against the live notebook.

    Returns ``{"state": ..., "detail": ...}`` where state is:
      - ``"none"``    — no notebook attached (nothing to compare);
      - ``"unknown"`` — a notebook is declared but not readable;
      - ``"never"``   — notebook present but the site was never rendered from it;
      - ``"fresh"``   — recorded vintage matches the live notebook;
      - ``"stale"``   — the notebook has moved on since the render.
    Never a hard failure — staleness is advisory.
    """
    nb = m.notebook_dir
    if not nb or not m.notebook:
        return {"state": "none", "detail": ""}
    live = flip_read.read_vintage(nb)
    if live is None:
        return {"state": "unknown", "detail": f"notebook at {m.notebook} is not readable"}
    if not m.rendered_uid and not m.rendered_updated:
        return {
            "state": "never",
            "detail": "site has no recorded notebook vintage — run `artoo provenance`",
        }
    if m.rendered_uid and live.get("uid") and m.rendered_uid != live["uid"]:
        return {
            "state": "stale",
            "detail": (
                f"rendered from notebook {m.rendered_uid}, but the attached "
                f"notebook is {live['uid']} — a different notebook"
            ),
        }
    if m.rendered_updated != live.get("updated", ""):
        return {
            "state": "stale",
            "detail": (
                f"rendered from {m.rendered_updated or '(unstamped)'}, "
                f"notebook now updated {live.get('updated') or '(unstamped)'} — re-render"
            ),
        }
    return {"state": "fresh", "detail": f"render matches notebook {live.get('updated')}"}
